# Numpy 

### 1-D NumpY Array

In [1]:
import numpy as np 

In [3]:
oneDarray = np.array([1,2,3])
print(oneDarray)
print(oneDarray.ndim)

[1 2 3]
1


### 2-D NumpY Array

In [5]:
twoDarray = np.array([[2,3,4],[4,6,7]])
print(twoDarray)
print(twoDarray.ndim)

[[2 3 4]
 [4 6 7]]
2


### 3-D NumpY Array 

In [7]:
threeDarray = np.array([[[2,3,4],[4,6,7]],[[2,3,4],[4,6,7]]])
print(threeDarray)
print(threeDarray.ndim)

[[[2 3 4]
  [4 6 7]]

 [[2 3 4]
  [4 6 7]]]
3


### Indexation of Numpy Array

In [9]:
# 1-D NumpY Array (first element)
print(oneDarray)
print(oneDarray[0])

[1 2 3]
1


In [10]:
# 2-D NumpY Array (first element of second array)
print(twoDarray)
print(twoDarray[1,0])

[[2 3 4]
 [4 6 7]]
4


### Looping through a Numpy Array


In [11]:
# 1-D NumpY Array 
for i in oneDarray : 
    print(i)

1
2
3


In [12]:
# 2-D NumpY Array (first element)
for i in twoDarray:
    for j in i :
        print(j)

2
3
4
4
6
7


In [13]:
# 3-D NumpY Array (first element)
for i in threeDarray:
    for j in i:
        for k in j:
            print(k)

2
3
4
4
6
7
2
3
4
4
6
7
