# Mathematics for Data Science

NumPy provides us with a huge collection of high-level functions for multidimensional arrays.

### zeros()


The numpy.zeros() function is used to create a new array of given shape and type, filled with zeros. 


In [2]:
import numpy as np

In [7]:
# Create a 1D array of zeros with 5 elements
array_zeros = np.zeros(5)
print("1D Array of zeros:", array_zeros)


1D Array of zeros: [0. 0. 0. 0. 0.]


You can convert this list i int with astype()

In [5]:
array_zeros = np.zeros(5).astype(int)
print("1D Array of zeros:", array_zeros)

1D Array of zeros: [0 0 0 0 0]


### ones()

The numpy.zeros() function is used to create a new array of given shape and type, filled with zeros. 

In [8]:
arrayOne = np.ones(10)
print(arrayOne)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [9]:
arrayOne = np.ones(10).astype(int)
print(arrayOne)

[1 1 1 1 1 1 1 1 1 1]


### full()

Fill with specific values

In [10]:
arrayFive = np.full(7,5)
print(arrayFive)

[5 5 5 5 5 5 5]


### Arithmetic

In [11]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)



[[1 2 3]
 [4 5 6]]
[[3 4 5]
 [6 7 8]]


In [12]:
# Addition
matrix += 2
print(matrix)

[[ 5  6  7]
 [ 8  9 10]]


In [13]:
# Subtraction
matrix -= 2
print(matrix)

[[3 4 5]
 [6 7 8]]


In [14]:
# Multiplication
matrix *= 2
print(matrix)

[[ 6  8 10]
 [12 14 16]]


In [18]:
# division
matrix //= 2
print(matrix)

[[1 2 2]
 [3 3 4]]


In [17]:
# Sqrt
matrix **2 
print(matrix)

[[3 4 5]
 [6 7 8]]


### 
To perform element-wise operations (addition, multiplication, and division) on two matrices using NumPy

In [3]:
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Element-wise addition
addition = np.add(matrix1, matrix2)
print(addition)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [4]:
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Element-wise multiplication
multiplication = np.multiply(matrix1, matrix2)
print(multiplication)

In [6]:
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
# Element-wise division
division = np.divide(matrix1, matrix2)
print(division)

[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


### The minimum, maximum, sum, mean, standard deviation, and median of elements in a matrix using NumPy

In [7]:
import numpy as np

# Define the matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Minimum element
min_element = np.min(matrix)

# Maximum element
max_element = np.max(matrix)

# Sum of all elements
sum_elements = np.sum(matrix)

# Mean (average) of all elements
mean_element = np.mean(matrix)

# Standard deviation of all elements
std_deviation = np.std(matrix)

# Median of all elements
median_element = np.median(matrix)

print("Minimum element:", min_element)
print("Maximum element:", max_element)
print("Sum of all elements:", sum_elements)
print("Mean of all elements:", mean_element)
print("Standard deviation of all elements:", std_deviation)
print("Median of all elements:", median_element)


Minimum element: 1
Maximum element: 9
Sum of all elements: 45
Mean of all elements: 5.0
Standard deviation of all elements: 2.581988897471611
Median of all elements: 5.0
